//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Lite_AppWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(Lite.App), typeof(Lite.SingletonMono<Lite.App>));
		L.RegFunction("Initialize", Initialize);
		L.RegFunction("StartManagers", StartManagers);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("gameManager", get_gameManager, set_gameManager);
		L.RegVar("eventManager", get_eventManager, set_eventManager);
		L.RegVar("resManager", get_resManager, set_resManager);
		L.RegVar("luaManager", get_luaManager, set_luaManager);
		L.RegVar("uiManager", get_uiManager, set_uiManager);
		L.RegVar("networkManager", get_networkManager, set_networkManager);
		L.RegVar("entityManager", get_entityManager, set_entityManager);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Initialize(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Lite.App obj = (Lite.App)ToLua.CheckObject(L, 1, typeof(Lite.App));
			obj.Initialize();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int StartManagers(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Lite.App obj = (Lite.App)ToLua.CheckObject(L, 1, typeof(Lite.App));
			obj.StartManagers();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_gameManager(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, Lite.App.gameManager);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_eventManager(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, Lite.App.eventManager);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_resManager(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, Lite.App.resManager);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_luaManager(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, Lite.App.luaManager);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_uiManager(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, Lite.App.uiManager);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_networkManager(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, Lite.App.networkManager);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_entityManager(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, Lite.App.entityManager);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_gameManager(IntPtr L)
	{
		try
		{
			Lite.GameManager arg0 = (Lite.GameManager)ToLua.CheckObject(L, 2, typeof(Lite.GameManager));
			Lite.App.gameManager = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_eventManager(IntPtr L)
	{
		try
		{
			Lite.EventManager arg0 = (Lite.EventManager)ToLua.CheckObject(L, 2, typeof(Lite.EventManager));
			Lite.App.eventManager = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_resManager(IntPtr L)
	{
		try
		{
			Lite.ResourceManager arg0 = (Lite.ResourceManager)ToLua.CheckObject(L, 2, typeof(Lite.ResourceManager));
			Lite.App.resManager = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_luaManager(IntPtr L)
	{
		try
		{
			Lite.LuaManager arg0 = (Lite.LuaManager)ToLua.CheckObject(L, 2, typeof(Lite.LuaManager));
			Lite.App.luaManager = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_uiManager(IntPtr L)
	{
		try
		{
			Lite.UIManager arg0 = (Lite.UIManager)ToLua.CheckObject(L, 2, typeof(Lite.UIManager));
			Lite.App.uiManager = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_networkManager(IntPtr L)
	{
		try
		{
			Lite.NetworkManager arg0 = (Lite.NetworkManager)ToLua.CheckObject(L, 2, typeof(Lite.NetworkManager));
			Lite.App.networkManager = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_entityManager(IntPtr L)
	{
		try
		{
			Lite.EntityManager arg0 = (Lite.EntityManager)ToLua.CheckObject(L, 2, typeof(Lite.EntityManager));
			Lite.App.entityManager = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

