//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Locke_Singleton_Locke_ui_UIManagerWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(Locke.Singleton<Locke.ui.UIManager>), typeof(System.Object), "Singleton_Locke_ui_UIManager");
		L.RegFunction("New", _CreateLocke_Singleton_Locke_ui_UIManager);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("Instance", get_Instance, null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateLocke_Singleton_Locke_ui_UIManager(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				Locke.Singleton<Locke.ui.UIManager> obj = new Locke.Singleton<Locke.ui.UIManager>();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: Locke.Singleton<Locke.ui.UIManager>.New");
			}
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Instance(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, Locke.Singleton<Locke.ui.UIManager>.Instance);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

