//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Locke_AppWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(Locke.App), typeof(Locke.Singleton<Locke.App>));
		L.RegFunction("Inittialize", Inittialize);
		L.RegFunction("New", _CreateLocke_App);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateLocke_App(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				Locke.App obj = new Locke.App();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: Locke.App.New");
			}
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Inittialize(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Locke.App obj = (Locke.App)ToLua.CheckObject(L, 1, typeof(Locke.App));
			obj.Inittialize();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

