-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('chat_pb')


local TEST1MSG1 = protobuf.Descriptor();
local TEST1MSG1_TEXT_FIELD = protobuf.FieldDescriptor();
local TEST1MSG1_NUMBER_FIELD = protobuf.FieldDescriptor();
local TEST1MSG1_BIGNUMBER_FIELD = protobuf.FieldDescriptor();
local TEST1MSG2 = protobuf.Descriptor();
local TEST1MSG2_TEXT_FIELD = protobuf.FieldDescriptor();
local TEST1MSG2_NUMBER_FIELD = protobuf.FieldDescriptor();
local TEST1MSG2_BIGNUMBER_FIELD = protobuf.FieldDescriptor();
local TEST1MSG3 = protobuf.Descriptor();
local TEST1MSG3_TEXT_FIELD = protobuf.FieldDescriptor();
local TEST1MSG3_NUMBER_FIELD = protobuf.FieldDescriptor();
local TEST1MSG3_BIGNUMBER_FIELD = protobuf.FieldDescriptor();

TEST1MSG1_TEXT_FIELD.name = "text"
TEST1MSG1_TEXT_FIELD.full_name = ".LiteServer.Test1Msg1.text"
TEST1MSG1_TEXT_FIELD.number = 1
TEST1MSG1_TEXT_FIELD.index = 0
TEST1MSG1_TEXT_FIELD.label = 1
TEST1MSG1_TEXT_FIELD.has_default_value = false
TEST1MSG1_TEXT_FIELD.default_value = ""
TEST1MSG1_TEXT_FIELD.type = 9
TEST1MSG1_TEXT_FIELD.cpp_type = 9

TEST1MSG1_NUMBER_FIELD.name = "number"
TEST1MSG1_NUMBER_FIELD.full_name = ".LiteServer.Test1Msg1.number"
TEST1MSG1_NUMBER_FIELD.number = 2
TEST1MSG1_NUMBER_FIELD.index = 1
TEST1MSG1_NUMBER_FIELD.label = 1
TEST1MSG1_NUMBER_FIELD.has_default_value = false
TEST1MSG1_NUMBER_FIELD.default_value = 0
TEST1MSG1_NUMBER_FIELD.type = 5
TEST1MSG1_NUMBER_FIELD.cpp_type = 1

TEST1MSG1_BIGNUMBER_FIELD.name = "bignumber"
TEST1MSG1_BIGNUMBER_FIELD.full_name = ".LiteServer.Test1Msg1.bignumber"
TEST1MSG1_BIGNUMBER_FIELD.number = 3
TEST1MSG1_BIGNUMBER_FIELD.index = 2
TEST1MSG1_BIGNUMBER_FIELD.label = 1
TEST1MSG1_BIGNUMBER_FIELD.has_default_value = false
TEST1MSG1_BIGNUMBER_FIELD.default_value = 0
TEST1MSG1_BIGNUMBER_FIELD.type = 3
TEST1MSG1_BIGNUMBER_FIELD.cpp_type = 2

TEST1MSG1.name = "Test1Msg1"
TEST1MSG1.full_name = ".LiteServer.Test1Msg1"
TEST1MSG1.nested_types = {}
TEST1MSG1.enum_types = {}
TEST1MSG1.fields = {TEST1MSG1_TEXT_FIELD, TEST1MSG1_NUMBER_FIELD, TEST1MSG1_BIGNUMBER_FIELD}
TEST1MSG1.is_extendable = false
TEST1MSG1.extensions = {}
TEST1MSG2_TEXT_FIELD.name = "text"
TEST1MSG2_TEXT_FIELD.full_name = ".LiteServer.Test1Msg2.text"
TEST1MSG2_TEXT_FIELD.number = 1
TEST1MSG2_TEXT_FIELD.index = 0
TEST1MSG2_TEXT_FIELD.label = 1
TEST1MSG2_TEXT_FIELD.has_default_value = false
TEST1MSG2_TEXT_FIELD.default_value = ""
TEST1MSG2_TEXT_FIELD.type = 9
TEST1MSG2_TEXT_FIELD.cpp_type = 9

TEST1MSG2_NUMBER_FIELD.name = "number"
TEST1MSG2_NUMBER_FIELD.full_name = ".LiteServer.Test1Msg2.number"
TEST1MSG2_NUMBER_FIELD.number = 2
TEST1MSG2_NUMBER_FIELD.index = 1
TEST1MSG2_NUMBER_FIELD.label = 1
TEST1MSG2_NUMBER_FIELD.has_default_value = false
TEST1MSG2_NUMBER_FIELD.default_value = 0
TEST1MSG2_NUMBER_FIELD.type = 5
TEST1MSG2_NUMBER_FIELD.cpp_type = 1

TEST1MSG2_BIGNUMBER_FIELD.name = "bignumber"
TEST1MSG2_BIGNUMBER_FIELD.full_name = ".LiteServer.Test1Msg2.bignumber"
TEST1MSG2_BIGNUMBER_FIELD.number = 3
TEST1MSG2_BIGNUMBER_FIELD.index = 2
TEST1MSG2_BIGNUMBER_FIELD.label = 1
TEST1MSG2_BIGNUMBER_FIELD.has_default_value = false
TEST1MSG2_BIGNUMBER_FIELD.default_value = 0
TEST1MSG2_BIGNUMBER_FIELD.type = 3
TEST1MSG2_BIGNUMBER_FIELD.cpp_type = 2

TEST1MSG2.name = "Test1Msg2"
TEST1MSG2.full_name = ".LiteServer.Test1Msg2"
TEST1MSG2.nested_types = {}
TEST1MSG2.enum_types = {}
TEST1MSG2.fields = {TEST1MSG2_TEXT_FIELD, TEST1MSG2_NUMBER_FIELD, TEST1MSG2_BIGNUMBER_FIELD}
TEST1MSG2.is_extendable = false
TEST1MSG2.extensions = {}
TEST1MSG3_TEXT_FIELD.name = "text"
TEST1MSG3_TEXT_FIELD.full_name = ".LiteServer.Test1Msg3.text"
TEST1MSG3_TEXT_FIELD.number = 1
TEST1MSG3_TEXT_FIELD.index = 0
TEST1MSG3_TEXT_FIELD.label = 1
TEST1MSG3_TEXT_FIELD.has_default_value = false
TEST1MSG3_TEXT_FIELD.default_value = ""
TEST1MSG3_TEXT_FIELD.type = 9
TEST1MSG3_TEXT_FIELD.cpp_type = 9

TEST1MSG3_NUMBER_FIELD.name = "number"
TEST1MSG3_NUMBER_FIELD.full_name = ".LiteServer.Test1Msg3.number"
TEST1MSG3_NUMBER_FIELD.number = 2
TEST1MSG3_NUMBER_FIELD.index = 1
TEST1MSG3_NUMBER_FIELD.label = 1
TEST1MSG3_NUMBER_FIELD.has_default_value = false
TEST1MSG3_NUMBER_FIELD.default_value = 0
TEST1MSG3_NUMBER_FIELD.type = 5
TEST1MSG3_NUMBER_FIELD.cpp_type = 1

TEST1MSG3_BIGNUMBER_FIELD.name = "bignumber"
TEST1MSG3_BIGNUMBER_FIELD.full_name = ".LiteServer.Test1Msg3.bignumber"
TEST1MSG3_BIGNUMBER_FIELD.number = 3
TEST1MSG3_BIGNUMBER_FIELD.index = 2
TEST1MSG3_BIGNUMBER_FIELD.label = 1
TEST1MSG3_BIGNUMBER_FIELD.has_default_value = false
TEST1MSG3_BIGNUMBER_FIELD.default_value = 0
TEST1MSG3_BIGNUMBER_FIELD.type = 3
TEST1MSG3_BIGNUMBER_FIELD.cpp_type = 2

TEST1MSG3.name = "Test1Msg3"
TEST1MSG3.full_name = ".LiteServer.Test1Msg3"
TEST1MSG3.nested_types = {}
TEST1MSG3.enum_types = {}
TEST1MSG3.fields = {TEST1MSG3_TEXT_FIELD, TEST1MSG3_NUMBER_FIELD, TEST1MSG3_BIGNUMBER_FIELD}
TEST1MSG3.is_extendable = false
TEST1MSG3.extensions = {}

Test1Msg1 = protobuf.Message(TEST1MSG1)
Test1Msg2 = protobuf.Message(TEST1MSG2)
Test1Msg3 = protobuf.Message(TEST1MSG3)

