-- This file is generated by PBX. You should never modify it.

module('PBX')

MsgID =
{

	-- chat.proto
	Test1Msg1 = 1001,
	Test1Msg2 = 1002,
	Test1Msg3 = 1003,

	-- login.proto
	ExtraInfo = 2001,
	Login = 2002,
	TestMsg1 = 2003,
	TestMsg2 = 2004,
	TestMsg3 = 2005,

};
