-- This file is generated by PBX. You should never modify it.

module('PBX')

MsgID =
{

	-- chat.proto
	sendMsg = 1001,
	recvMsg = 1002,

	-- login.proto
	gcLoginRoleInfo = 2001,
	cgLogin = 2002,
	gcLoginRet = 2003,
	cgLogout = 2004,
	gcLogoutRet = 2005,
	cgEnterGame = 2006,
	gcEnterGameRet = 2007,

	-- scene.proto
	gcPlayerInfo = 3001,
	gcEnterScene = 3002,
	cgEnterSceneDone = 3003,
	cgExitScene = 3004,
	gcExitSceneRet = 3005,
	gcOtherEnterScene = 3006,
	gcNearbyPlayerInfo = 3007,
	cgMoveTo = 3008,
	gcMoveTo = 3009,

};
