-- This file is generated by PBX. You should never modify it.

module('PBX')

MsgID =
{

	-- chat.proto
	sendMsg = 1001,
	recvMsg = 1002,

	-- login.proto
	LoginRoleInfo = 2001,
	LoginRequest = 2002,
	LoginResponse = 2003,
	EnterGameRequest = 2004,
	EnterGameResponse = 2005,

	-- scene.proto
	MoveRequest = 3001,

};
