-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('proto_login_pb')


local EXTRAINFO = protobuf.Descriptor();
local EXTRAINFO_NUMBER_FIELD = protobuf.FieldDescriptor();
local LOGIN = protobuf.Descriptor();
local LOGIN_NAME_FIELD = protobuf.FieldDescriptor();
local LOGIN_PASSWORD_FIELD = protobuf.FieldDescriptor();
local LOGIN_INFOS_FIELD = protobuf.FieldDescriptor();

EXTRAINFO_NUMBER_FIELD.name = "number"
EXTRAINFO_NUMBER_FIELD.full_name = ".LiteServer.ExtraInfo.number"
EXTRAINFO_NUMBER_FIELD.number = 1
EXTRAINFO_NUMBER_FIELD.index = 0
EXTRAINFO_NUMBER_FIELD.label = 1
EXTRAINFO_NUMBER_FIELD.has_default_value = false
EXTRAINFO_NUMBER_FIELD.default_value = 0
EXTRAINFO_NUMBER_FIELD.type = 5
EXTRAINFO_NUMBER_FIELD.cpp_type = 1

EXTRAINFO.name = "ExtraInfo"
EXTRAINFO.full_name = ".LiteServer.ExtraInfo"
EXTRAINFO.nested_types = {}
EXTRAINFO.enum_types = {}
EXTRAINFO.fields = {EXTRAINFO_NUMBER_FIELD}
EXTRAINFO.is_extendable = false
EXTRAINFO.extensions = {}
LOGIN_NAME_FIELD.name = "name"
LOGIN_NAME_FIELD.full_name = ".LiteServer.Login.name"
LOGIN_NAME_FIELD.number = 1
LOGIN_NAME_FIELD.index = 0
LOGIN_NAME_FIELD.label = 1
LOGIN_NAME_FIELD.has_default_value = false
LOGIN_NAME_FIELD.default_value = ""
LOGIN_NAME_FIELD.type = 9
LOGIN_NAME_FIELD.cpp_type = 9

LOGIN_PASSWORD_FIELD.name = "password"
LOGIN_PASSWORD_FIELD.full_name = ".LiteServer.Login.password"
LOGIN_PASSWORD_FIELD.number = 2
LOGIN_PASSWORD_FIELD.index = 1
LOGIN_PASSWORD_FIELD.label = 1
LOGIN_PASSWORD_FIELD.has_default_value = false
LOGIN_PASSWORD_FIELD.default_value = ""
LOGIN_PASSWORD_FIELD.type = 9
LOGIN_PASSWORD_FIELD.cpp_type = 9

LOGIN_INFOS_FIELD.name = "infos"
LOGIN_INFOS_FIELD.full_name = ".LiteServer.Login.infos"
LOGIN_INFOS_FIELD.number = 3
LOGIN_INFOS_FIELD.index = 2
LOGIN_INFOS_FIELD.label = 3
LOGIN_INFOS_FIELD.has_default_value = false
LOGIN_INFOS_FIELD.default_value = {}
LOGIN_INFOS_FIELD.message_type = EXTRAINFO
LOGIN_INFOS_FIELD.type = 11
LOGIN_INFOS_FIELD.cpp_type = 10

LOGIN.name = "Login"
LOGIN.full_name = ".LiteServer.Login"
LOGIN.nested_types = {}
LOGIN.enum_types = {}
LOGIN.fields = {LOGIN_NAME_FIELD, LOGIN_PASSWORD_FIELD, LOGIN_INFOS_FIELD}
LOGIN.is_extendable = false
LOGIN.extensions = {}

ExtraInfo = protobuf.Message(EXTRAINFO)
Login = protobuf.Message(LOGIN)

