-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('scene_pb')


local MOVEREQUEST = protobuf.Descriptor();
local MOVEREQUEST_X_FIELD = protobuf.FieldDescriptor();
local MOVEREQUEST_Y_FIELD = protobuf.FieldDescriptor();
local MOVEREQUEST_Z_FIELD = protobuf.FieldDescriptor();

MOVEREQUEST_X_FIELD.name = "x"
MOVEREQUEST_X_FIELD.full_name = ".Lite.MoveRequest.x"
MOVEREQUEST_X_FIELD.number = 1
MOVEREQUEST_X_FIELD.index = 0
MOVEREQUEST_X_FIELD.label = 1
MOVEREQUEST_X_FIELD.has_default_value = false
MOVEREQUEST_X_FIELD.default_value = 0.0
MOVEREQUEST_X_FIELD.type = 2
MOVEREQUEST_X_FIELD.cpp_type = 6

MOVEREQUEST_Y_FIELD.name = "y"
MOVEREQUEST_Y_FIELD.full_name = ".Lite.MoveRequest.y"
MOVEREQUEST_Y_FIELD.number = 2
MOVEREQUEST_Y_FIELD.index = 1
MOVEREQUEST_Y_FIELD.label = 1
MOVEREQUEST_Y_FIELD.has_default_value = false
MOVEREQUEST_Y_FIELD.default_value = 0.0
MOVEREQUEST_Y_FIELD.type = 2
MOVEREQUEST_Y_FIELD.cpp_type = 6

MOVEREQUEST_Z_FIELD.name = "z"
MOVEREQUEST_Z_FIELD.full_name = ".Lite.MoveRequest.z"
MOVEREQUEST_Z_FIELD.number = 3
MOVEREQUEST_Z_FIELD.index = 2
MOVEREQUEST_Z_FIELD.label = 1
MOVEREQUEST_Z_FIELD.has_default_value = false
MOVEREQUEST_Z_FIELD.default_value = 0.0
MOVEREQUEST_Z_FIELD.type = 2
MOVEREQUEST_Z_FIELD.cpp_type = 6

MOVEREQUEST.name = "MoveRequest"
MOVEREQUEST.full_name = ".Lite.MoveRequest"
MOVEREQUEST.nested_types = {}
MOVEREQUEST.enum_types = {}
MOVEREQUEST.fields = {MOVEREQUEST_X_FIELD, MOVEREQUEST_Y_FIELD, MOVEREQUEST_Z_FIELD}
MOVEREQUEST.is_extendable = false
MOVEREQUEST.extensions = {}

MoveRequest = protobuf.Message(MOVEREQUEST)

